%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(tutorial_constants).

-include("tutorial_types.hrl").

-export([mapconstant/1, mapconstant/2]).

mapconstant("hello") -> "world";
mapconstant("goodnight") -> "moon".

mapconstant("hello", _) -> "world";
mapconstant("goodnight", _) -> "moon";
mapconstant(_, Default) -> Default.

