%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(tutorial_types).

-include("tutorial_types.hrl").

-export([struct_info/1, struct_info_ext/1, enum_info/1, enum_names/0, struct_names/0, exception_names/0]).

struct_info('Work') ->
  {struct, [{1, i32},
          {2, i32},
          {3, i32},
          {4, string}]}
;

struct_info('InvalidOperation') ->
  {struct, [{1, i32},
          {2, string}]}
;

struct_info(_) -> erlang:error(function_clause).

struct_info_ext('Work') ->
  {struct, [{1, undefined, i32, 'num1', 0},
          {2, undefined, i32, 'num2', undefined},
          {3, undefined, i32, 'op', undefined},
          {4, optional, string, 'comment', undefined}]}
;

struct_info_ext('InvalidOperation') ->
  {struct, [{1, undefined, i32, 'whatOp', undefined},
          {2, undefined, string, 'why', undefined}]}
;

struct_info_ext(_) -> erlang:error(function_clause).

struct_names() ->
  ['Work'].

enum_info('Operation') ->
  [
    {'ADD', 1},
    {'SUBTRACT', 2},
    {'MULTIPLY', 3},
    {'DIVIDE', 4}
  ];

enum_info(_) -> erlang:error(function_clause).

enum_names() ->
  ['Operation'].

exception_names() ->
  ['InvalidOperation'].

