%%
%% Autogenerated by Thrift Compiler (0.11.0)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%


-include("tutorial_types.hrl").

-define(TUTORIAL_INT32CONSTANT, 9853).

-define(TUTORIAL_MAPCONSTANT, maps:from_list([{"hello","world"},{"goodnight","moon"}])).

